# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CodeObfuscation' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CodeObfuscation
  pod 'FMDB', '~> 2.7.2'
  pod 'BuildSql', '~> 1.1.0’

end
